on:
  workflow_call:
    inputs:
      solution_name:
        description: 'Nome da solução a ser compilada'
        required: true
        type: string
      test_path:
        description: 'Caminho para os testes'
        required: true
        type: string
      exe_path:
        description: 'Caminho para o executável'
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        description: 'Token do GitHub'
        required: true

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.solution_name }}
          path: ${{ inputs.test_path }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: ${{ inputs.exe_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
