on:
  workflow_call:
    inputs:
      exe_path:
        description: 'Caminho para o executável'
        required: true
        type: string

jobs:
  release:
    runs-on: windows-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Find Executable
        run: |
          $exe = Get-ChildItem -Path . -Recurse -Filter *.exe | Where-Object { $_.FullName -notmatch '\\obj\\' } | Select-Object -First 1
          if ($null -eq $exe) {
            Write-Error "Nenhum executável encontrado!"
          }
          echo "EXE_PATH=$($exe.FullName)" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: ${{ inputs.exe_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
