# on:
#   workflow_call:
#     inputs:
     
#       build_configuration:
#         description: 'Configuração de build (Debug ou Release)'
#         required: true
#         type: string

# jobs:
#   test:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

      

