on:
  workflow_call:
    inputs:
    secrets:
      SONAR_TOKEN:
        description: 'Token do SonarQube'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Build the project
    - name: Build solution
      run: |
        $solution = Get-ChildItem -Path . -Recurse -Filter "*.sln" | Select-Object -First 1
        if ($null -eq $solution) {
          Write-Error "Nenhum arquivo .sln encontrado no repositório."
        }
        msbuild $solution.FullName /p:Configuration=Release
      continue-on-error: false
    
    # Run unit tests
    - name: Run tests
      run: |
        $testProjects = Get-ChildItem -Path . -Recurse -Filter "*.csproj" | Where-Object { $_.FullName -match "\.Tests\.csproj$" }
        foreach ($project in $testProjects) {
          dotnet test $project.FullName --configuration=Release
        }
      shell: pwsh

    # Setup NuGet
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Oficial SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v5.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
         -Dsonar.organization='migracaodotnetforms'
         -Dsonar.projectKey=${{ github.event.repository.name }}
         -Dsonar.verbose=true
         -Dsonar.exclusions=**/bin/**/*,**/obj/**/*,**/packages/**/*,**/test/**/*

    - name: Save Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Save  Build-Artifacts
        path: 





